---

- hosts: all

  vars_prompt:
    - name: "mas_email"
      prompt: "What is your Mac App Store E-mail"
      when: mas_account_result.rc == 1

    - name: "mas_password"
      prompt: "What is your Mac App Store Password"
      when: mas_account_result.rc == 1

  tasks:
    - name: Ensure MAS is installed.
      homebrew: name=mas state=present

    - name: Get MAS account status
      shell: 'mas account'
      register: mas_account_result
      failed_when: mas_account_result.rc > 1
      changed_when: false

    - name: Sign in to MAS when email and password are provided.
      shell: 'mas signin "{{ mas_email }}" "{{ mas_password }}"'
      register: mas_signin_result
      when: mas_account_result.rc == 1 and mas_email != '' and mas_password != ''

    - name: List installed MAS apps.
      command: mas list
      register: mas_list
      always_run: yes
      changed_when: false

    - name: Installing Xcode from MAS (If it fails means Apple requires 2FA for installing Xcode)
      command: mas install 497799835
